In [1]:
import numpy as np
import yfinance as yf
import pandas as pd

In [2]:
tickers = [
    "SPY",   # S&P 500 ETF
    "AAPL",  # Apple
    "NVDA",  # Nvidia
    "MSFT",  # Microsoft
    "JPM",   # JPMorgan Chase
    "BAC",   # Bank of America
    "SHEL",  # Shell
    "XOM",   # Exxon Mobil
    "GLD",   # SPDR Gold Shares
    "BZ=F",  # Brent crude oil futures
    "NG=F"   # Natural gas (Henry Hub) futures
]

START_DATE = "2010-01-01"
END_DATE = "2026-09-14"

In [3]:
data = yf.download(
    tickers,
    start=START_DATE,
    end=END_DATE,
    interval="1d",
    auto_adjust=True,
    progress=False
)

In [4]:
data

Price            Close                                                 \
Ticker            AAPL        BAC        BZ=F         GLD         JPM
Date
2010-01-04    6.400960  11.977121   80.120003  109.800003   28.152369
2010-01-05    6.412026  12.366441   80.589996  109.699997   28.697687
2010-01-06    6.310035  12.511477   81.889999  111.510002   28.855362
2010-01-07    6.298369  12.923691   81.510002  110.820000   29.426968
2010-01-08    6.340243  12.809187   81.370003  111.370003   29.354698
...                ...        ...         ...         ...         ...
2026-09-04  319.970001  62.680000   96.279999  406.769989  358.640015
2026-09-08  316.220001  62.389999   97.919998  399.720001  353.510010
2026-09-09  315.339996  62.669998  101.209999  403.350006  354.709991
2026-09-10  326.570007  62.560001  107.629997  396.359985  353.559998
2026-09-11  332.269989  62.689999  104.610001  398.769989  356.230011

Price                                                             ...  \
Ticker            MSFT   NG=F        NVDA       SHEL         SPY  ...
Date                                                              ...
2010-01-04   22.984238  5.884    0.422817  26.799501   84.578461  ...
2010-01-05   22.991665  5.637    0.428991  26.829590   84.802383  ...
2010-01-06   22.850565  6.009    0.431736  26.610382   84.862030  ...
2010-01-07   22.612928  5.806    0.423275  26.481426   85.220306  ...
2010-01-08   22.768873  5.749    0.424189  26.442736   85.503899  ...
...                ...    ...         ...        ...         ...  ...
2026-09-04  499.700012  2.975  230.102524  92.949997  770.190002  ...
2026-09-08  493.950012  2.916  225.477692  95.320000  765.960022  ...
2026-09-09  491.649994  2.822  223.419998  95.599998  762.400024  ...
2026-09-10  492.440002  2.834  218.360001  95.959999  757.830017  ...
2026-09-11  495.630005  2.831  218.289993  96.769997  764.289978  ...

Price            Volume                                               \
Ticker              BAC     BZ=F         GLD         JPM        MSFT
Date
2010-01-04  180845200.0     97.0  16224100.0  35460500.0  38409100.0
2010-01-05  209521300.0     97.0  14213100.0  41208300.0  49749600.0
2010-01-06  205257900.0      7.0  24981900.0  27729000.0  58182400.0
2010-01-07  320868400.0      7.0  13609800.0  44864700.0  50559700.0
2010-01-08  220104700.0      7.0  15894600.0  33110100.0  51197400.0
...                 ...      ...         ...         ...         ...
2026-09-04   26587200.0  35106.0   9813200.0   4873500.0  18101800.0
2026-09-08   28338000.0  71135.0   8992200.0   5631400.0  18882300.0
2026-09-09   36015200.0  51567.0   8188400.0   6318200.0  12889600.0
2026-09-10   29359100.0  72538.0  10202900.0   4184200.0  16038800.0
2026-09-11   28873700.0  61285.0  10963000.0   5354600.0  14510500.0

Price
Ticker          NG=F         NVDA       SHEL          SPY         XOM
Date
2010-01-04   78858.0  800204000.0  1643003.0  118944600.0  27809100.0
2010-01-05   99492.0  728648000.0  1718458.0  111579900.0  30174700.0
2010-01-06  140611.0  649168000.0  3040554.0  116074400.0  35044700.0
2010-01-07  135113.0  547792000.0  1033089.0  131091100.0  27192100.0
2010-01-08  101153.0  478168000.0  1438017.0  126402800.0  24891800.0
...              ...          ...        ...          ...         ...
2026-09-04  150051.0  135352400.0  6849003.0   34054200.0  16206400.0
2026-09-08  248447.0  122965600.0  7425065.0   44746100.0  12607700.0
2026-09-09  178990.0   82955500.0  8384823.0   32812400.0  13124000.0
2026-09-10  174179.0  105768000.0  6483274.0   42740400.0  16615300.0
2026-09-11  128318.0   89060100.0  5251076.0   45512700.0  11362400.0

[4201 rows x 55 columns]

In [5]:
data = data["Close"].sort_index()

In [6]:
data.tail()

Ticker,AAPL,BAC,BZ=F,GLD,JPM,MSFT,NG=F,NVDA,SHEL,SPY,XOM
Date,,,,,,,,,,,
2026-09-04,319.970001,62.680000,96.279999,406.769989,358.640015,499.700012,2.975,230.102524,92.949997,770.190002,159.470001
2026-09-08,316.220001,62.389999,97.919998,399.720001,353.510010,493.950012,2.916,225.477692,95.320000,765.960022,160.660004
2026-09-09,315.339996,62.669998,101.209999,403.350006,354.709991,491.649994,2.822,223.419998,95.599998,762.400024,164.229996
2026-09-10,326.570007,62.560001,107.629997,396.359985,353.559998,492.440002,2.834,218.360001,95.959999,757.830017,165.229996
2026-09-11,332.269989,62.689999,104.610001,398.769989,356.230011,495.630005,2.831,218.289993,96.769997,764.289978,165.990005

In [7]:
data

Ticker,AAPL,BAC,BZ=F,GLD,JPM,MSFT,NG=F,NVDA,SHEL,SPY,XOM
Date,,,,,,,,,,,
2010-01-04,6.400960,11.977121,80.120003,109.800003,28.152369,22.984238,5.884,0.422817,26.799501,84.578461,37.136799
2010-01-05,6.412026,12.366441,80.589996,109.699997,28.697687,22.991665,5.637,0.428991,26.829590,84.802383,37.281822
2010-01-06,6.310035,12.511477,81.889999,111.510002,28.855362,22.850565,6.009,0.431736,26.610382,84.862030,37.604042
2010-01-07,6.298369,12.923691,81.510002,110.820000,29.426968,22.612928,5.806,0.423275,26.481426,85.220306,37.485897
2010-01-08,6.340243,12.809187,81.370003,111.370003,29.354698,22.768873,5.749,0.424189,26.442736,85.503899,37.335526
...,...,...,...,...,...,...,...,...,...,...,...
2026-09-04,319.970001,62.680000,96.279999,406.769989,358.640015,499.700012,2.975,230.102524,92.949997,770.190002,159.470001
2026-09-08,316.220001,62.389999,97.919998,399.720001,353.510010,493.950012,2.916,225.477692,95.320000,765.960022,160.660004
2026-09-09,315.339996,62.669998,101.209999,403.350006,354.709991,491.649994,2.822,223.419998,95.599998,762.400024,164.229996
2026-09-10,326.570007,62.560001,107.629997,396.359985,353.559998,492.440002,2.834,218.360001,95.959999,757.830017,165.229996
2026-09-11,332.269989,62.689999,104.610001,398.769989,356.230011,495.630005,2.831,218.289993,96.769997,764.289978,165.990005

In [8]:
# date orrdre croissant
data.tail(10)

Ticker,AAPL,BAC,BZ=F,GLD,JPM,MSFT,NG=F,NVDA,SHEL,SPY,XOM
Date,,,,,,,,,,,
2026-08-28,319.700012,62.003654,89.309998,408.890015,357.619995,513.530029,2.888,217.306839,90.910004,769.349976,156.710007
2026-08-31,316.850006,61.625580,90.489998,408.420013,356.019989,507.290009,2.935,220.533234,91.449997,767.049988,160.949997
2026-09-01,325.130005,61.675331,94.650002,396.750000,354.950012,501.019989,2.904,217.196976,93.510002,761.780029,164.550003
2026-09-02,324.959991,62.282230,95.629997,402.779999,356.220001,496.820007,2.956,224.159180,92.800003,765.159973,164.149994
2026-09-03,328.209991,62.719997,95.519997,410.220001,362.059998,510.119995,2.913,228.194656,92.330002,773.169983,162.210007
2026-09-04,319.970001,62.680000,96.279999,406.769989,358.640015,499.700012,2.975,230.102524,92.949997,770.190002,159.470001
2026-09-08,316.220001,62.389999,97.919998,399.720001,353.510010,493.950012,2.916,225.477692,95.320000,765.960022,160.660004
2026-09-09,315.339996,62.669998,101.209999,403.350006,354.709991,491.649994,2.822,223.419998,95.599998,762.400024,164.229996
2026-09-10,326.570007,62.560001,107.629997,396.359985,353.559998,492.440002,2.834,218.360001,95.959999,757.830017,165.229996
2026-09-11,332.269989,62.689999,104.610001,398.769989,356.230011,495.630005,2.831,218.289993,96.769997,764.289978,165.990005

In [9]:
data.rename(columns={
    
    "SPY": "S&P 500",
    "AAPL": "Apple",
    "NVDA": "Nvidia",
    "MSFT": "Microsoft",
    "JPM": "JPMorgan",
    "BAC": "Bank of America",
    "SHEL": "Shell",
    "XOM": "Exxon Mobil",
    "GLD": "Gold",
    "BZ=F": "Oil",
    "NG=F": "Gas"
    
},inplace = True)

In [10]:
data.head(10)

Ticker,Apple,Bank of America,Oil,Gold,JPMorgan,Microsoft,Gas,Nvidia,Shell,S&P 500,Exxon Mobil
Date,,,,,,,,,,,
2010-01-04,6.400960,11.977121,80.120003,109.800003,28.152369,22.984238,5.884,0.422817,26.799501,84.578461,37.136799
2010-01-05,6.412026,12.366441,80.589996,109.699997,28.697687,22.991665,5.637,0.428991,26.829590,84.802383,37.281822
2010-01-06,6.310035,12.511477,81.889999,111.510002,28.855362,22.850565,6.009,0.431736,26.610382,84.862030,37.604042
2010-01-07,6.298369,12.923691,81.510002,110.820000,29.426968,22.612928,5.806,0.423275,26.481426,85.220306,37.485897
2010-01-08,6.340243,12.809187,81.370003,111.370003,29.354698,22.768873,5.749,0.424189,26.442736,85.503899,37.335526
2010-01-11,6.284314,12.923691,80.970001,112.849998,29.256140,22.479252,5.454,0.418244,26.855375,85.623306,37.754414
2010-01-12,6.212828,12.488577,79.300003,110.489998,28.572865,22.330730,5.591,0.404066,26.249323,84.824760,37.566448
2010-01-13,6.300462,12.687056,78.309998,111.540001,29.072172,22.538670,5.733,0.409554,26.266521,85.541245,37.416065
2010-01-14,6.263973,12.839724,77.820000,112.029999,29.361242,22.991665,5.588,0.403151,26.202055,85.772583,37.421452
2010-01-15,6.159291,12.412243,77.110001,110.860001,28.697687,22.917398,5.691,0.391260,26.008629,84.809860,37.115322

In [11]:
# savoir le nombre de NaN
data.isna().sum()

Ticker
Apple               3
Bank of America     3
Oil                34
Gold                3
JPMorgan            3
Microsoft           3
Gas                 2
Nvidia              3
Shell               3
S&P 500             3
Exxon Mobil         3
dtype: int64

In [12]:
data.dropna(inplace=True)
data.isna().sum()

Ticker
Apple              0
Bank of America    0
Oil                0
Gold               0
JPMorgan           0
Microsoft          0
Gas                0
Nvidia             0
Shell              0
S&P 500            0
Exxon Mobil        0
dtype: int64

In [13]:
data

Ticker,Apple,Bank of America,Oil,Gold,JPMorgan,Microsoft,Gas,Nvidia,Shell,S&P 500,Exxon Mobil
Date,,,,,,,,,,,
2010-01-04,6.400960,11.977121,80.120003,109.800003,28.152369,22.984238,5.884,0.422817,26.799501,84.578461,37.136799
2010-01-05,6.412026,12.366441,80.589996,109.699997,28.697687,22.991665,5.637,0.428991,26.829590,84.802383,37.281822
2010-01-06,6.310035,12.511477,81.889999,111.510002,28.855362,22.850565,6.009,0.431736,26.610382,84.862030,37.604042
2010-01-07,6.298369,12.923691,81.510002,110.820000,29.426968,22.612928,5.806,0.423275,26.481426,85.220306,37.485897
2010-01-08,6.340243,12.809187,81.370003,111.370003,29.354698,22.768873,5.749,0.424189,26.442736,85.503899,37.335526
...,...,...,...,...,...,...,...,...,...,...,...
2026-09-04,319.970001,62.680000,96.279999,406.769989,358.640015,499.700012,2.975,230.102524,92.949997,770.190002,159.470001
2026-09-08,316.220001,62.389999,97.919998,399.720001,353.510010,493.950012,2.916,225.477692,95.320000,765.960022,160.660004
2026-09-09,315.339996,62.669998,101.209999,403.350006,354.709991,491.649994,2.822,223.419998,95.599998,762.400024,164.229996
2026-09-10,326.570007,62.560001,107.629997,396.359985,353.559998,492.440002,2.834,218.360001,95.959999,757.830017,165.229996
2026-09-11,332.269989,62.689999,104.610001,398.769989,356.230011,495.630005,2.831,218.289993,96.769997,764.289978,165.990005

In [14]:
data.columns

Index(['Apple', 'Bank of America', 'Oil', 'Gold', 'JPMorgan', 'Microsoft',
       'Gas', 'Nvidia', 'Shell', 'S&P 500', 'Exxon Mobil'],
      dtype='object', name='Ticker')

In [15]:
column = ["S&P 500", "Nvidia", "Apple", "Microsoft", "JPMorgan", "Bank of America", "Exxon Mobil", "Shell", "Gold", "Oil", "Gas" ]
data = data[column]

In [16]:
data

Ticker,S&P 500,Nvidia,Apple,Microsoft,JPMorgan,Bank of America,Exxon Mobil,Shell,Gold,Oil,Gas
Date,,,,,,,,,,,
2010-01-04,84.578461,0.422817,6.400960,22.984238,28.152369,11.977121,37.136799,26.799501,109.800003,80.120003,5.884
2010-01-05,84.802383,0.428991,6.412026,22.991665,28.697687,12.366441,37.281822,26.829590,109.699997,80.589996,5.637
2010-01-06,84.862030,0.431736,6.310035,22.850565,28.855362,12.511477,37.604042,26.610382,111.510002,81.889999,6.009
2010-01-07,85.220306,0.423275,6.298369,22.612928,29.426968,12.923691,37.485897,26.481426,110.820000,81.510002,5.806
2010-01-08,85.503899,0.424189,6.340243,22.768873,29.354698,12.809187,37.335526,26.442736,111.370003,81.370003,5.749
...,...,...,...,...,...,...,...,...,...,...,...
2026-09-04,770.190002,230.102524,319.970001,499.700012,358.640015,62.680000,159.470001,92.949997,406.769989,96.279999,2.975
2026-09-08,765.960022,225.477692,316.220001,493.950012,353.510010,62.389999,160.660004,95.320000,399.720001,97.919998,2.916
2026-09-09,762.400024,223.419998,315.339996,491.649994,354.709991,62.669998,164.229996,95.599998,403.350006,101.209999,2.822
2026-09-10,757.830017,218.360001,326.570007,492.440002,353.559998,62.560001,165.229996,95.959999,396.359985,107.629997,2.834
2026-09-11,764.289978,218.289993,332.269989,495.630005,356.230011,62.689999,165.990005,96.769997,398.769989,104.610001,2.831

In [ ]:
# dataframe avec les rendemtns
returns = data.pct_change().dropna()
returns

Ticker,S&P 500,Nvidia,Apple,Microsoft,JPMorgan,Bank of America,Exxon Mobil,Shell,Gold,Oil,Gas
Date,,,,,,,,,,,
2010-01-05,0.002648,0.014603,0.001729,0.000323,0.019370,0.032505,0.003905,0.001123,-0.000911,0.005866,-0.041978
2010-01-06,0.000703,0.006397,-0.015906,-0.006137,0.005494,0.011728,0.008643,-0.008170,0.016500,0.016131,0.065993
2010-01-07,0.004222,-0.019598,-0.001849,-0.010400,0.019809,0.032947,-0.003142,-0.004846,-0.006188,-0.004640,-0.033783
2010-01-08,0.003328,0.002161,0.006648,0.006896,-0.002456,-0.008860,-0.004011,-0.001461,0.004963,-0.001718,-0.009817
2010-01-11,0.001397,-0.014016,-0.008821,-0.012720,-0.003358,0.008939,0.011220,0.015605,0.013289,-0.004916,-0.051313
...,...,...,...,...,...,...,...,...,...,...,...
2026-09-04,-0.003854,0.008361,-0.025106,-0.020427,-0.009446,-0.000638,-0.016892,0.006715,-0.008410,0.007956,0.021284
2026-09-08,-0.005492,-0.020099,-0.011720,-0.011507,-0.014304,-0.004627,0.007462,0.025498,-0.017332,0.017034,-0.019832
2026-09-09,-0.004648,-0.009126,-0.002783,-0.004656,0.003394,0.004488,0.022221,0.002937,0.009081,0.033599,-0.032236
2026-09-10,-0.005994,-0.022648,0.035612,0.001607,-0.003242,-0.001755,0.006089,0.003766,-0.017330,0.063432,0.004252
2026-09-11,0.008524,-0.000321,0.017454,0.006478,0.007552,0.002078,0.004600,0.008441,0.006080,-0.028059,-0.001059

In [ ]:
# on ne garde que les jours ou rendement S&P inf à 3%
crash_days = returns.loc[returns["S&P 500"]<=-0.03]
crash_days

Ticker,S&P 500,Nvidia,Apple,Microsoft,JPMorgan,Bank of America,Exxon Mobil,Shell,Gold,Oil,Gas
Date,,,,,,,,,,,
2010-02-04,-0.030866,-0.058057,-0.036039,-0.027594,-0.048151,-0.050225,-0.028228,-0.040719,-0.039834,-0.049921,-0.000554
2010-05-06,-0.033213,-0.020690,-0.038048,-0.029146,-0.042693,-0.071306,-0.034457,-0.034561,0.029542,-0.033652,-0.015535
2010-05-20,-0.037760,-0.023511,-0.042603,-0.040014,-0.039360,-0.061925,-0.033947,-0.017351,-0.006774,-0.025105,-0.012506
2010-06-04,-0.035137,-0.047245,-0.027212,-0.039836,-0.037851,-0.029095,-0.032976,-0.042175,0.010427,-0.044026,0.022814
2010-06-29,-0.030875,-0.055855,-0.045211,-0.041135,-0.038402,-0.043963,-0.020181,-0.031593,0.001487,-0.027710,-0.035828
2011-08-04,-0.046841,-0.095206,-0.038719,-0.036404,-0.049624,-0.074424,-0.049923,-0.070524,-0.005264,-0.052813,-0.036430
2011-08-08,-0.065123,-0.078764,-0.054628,-0.046729,-0.094149,-0.203182,-0.061882,-0.068168,0.033199,-0.051477,-0.001522
2011-08-10,-0.044178,-0.045630,-0.027593,-0.053948,-0.055769,-0.109210,-0.044120,-0.040356,0.035407,0.040070,0.002253
2011-08-18,-0.043118,-0.067916,-0.037825,-0.022970,-0.037736,-0.060322,-0.043420,-0.036077,0.018920,-0.032640,-0.010425
2011-09-22,-0.032325,-0.066344,-0.025040,-0.035783,-0.035267,-0.050157,-0.037932,-0.023753,-0.026154,-0.044128,-0.006702
2011-11-09,-0.036910,-0.050398,-0.026955,-0.035346,-0.070817,-0.056661,-0.029715,-0.049910,-0.008413,-0.023391,-0.024833
2015-08-21,-0.030103,-0.031137,-0.061163,-0.056723,-0.035487,-0.037081,-0.032721,-0.032294,0.006248,-0.024882,-0.028675
2015-08-24,-0.042107,-0.035398,-0.024962,-0.032273,-0.052673,-0.050310,-0.047276,-0.051678,-0.005399,-0.060933,-0.009716
2016-06-24,-0.035909,-0.056919,-0.028096,-0.040069,-0.069477,-0.074074,-0.026253,-0.064347,0.049038,-0.049106,-0.013343
2018-02-05,-0.041822,-0.084875,-0.024985,-0.041186,-0.047952,-0.052895,-0.056903,-0.041010,0.002532,-0.013998,-0.034786
2018-02-08,-0.037509,-0.049301,-0.027517,-0.051334,-0.044210,-0.048320,-0.011308,-0.022116,0.001523,-0.010685,-0.001850
2018-10-10,-0.031664,-0.074753,-0.046326,-0.054338,-0.026633,-0.024683,-0.023003,-0.020202,0.002487,-0.022471,0.005511
2018-10-24,-0.030299,-0.097937,-0.034302,-0.053469,-0.018623,-0.030718,-0.027806,-0.027888,0.002320,-0.003532,-0.014321
2018-12-04,-0.032402,-0.076041,-0.043989,-0.031849,-0.044637,-0.054310,-0.022039,-0.018597,0.006099,0.006322,0.027195
2019-08-05,-0.030073,-0.064520,-0.052348,-0.034258,-0.029753,-0.044248,-0.020488,-0.022941,0.013982,-0.033608,-0.024045
2020-02-24,-0.033165,-0.070697,-0.047500,-0.043116,-0.026876,-0.047439,-0.046846,-0.038438,0.008985,-0.037607,-0.040945
2020-02-25,-0.030302,-0.041093,-0.033872,-0.016502,-0.044643,-0.050412,-0.038325,-0.029188,-0.017874,-0.023979,0.010947
2020-02-27,-0.044912,-0.055666,-0.065368,-0.070459,-0.041614,-0.048971,-0.060177,-0.039563,0.000195,-0.023395,-0.037891
2020-03-05,-0.033242,-0.039436,-0.032437,-0.025095,-0.049061,-0.050691,-0.044067,-0.034658,0.021601,-0.022296,-0.030104
2020-03-09,-0.078094,-0.077432,-0.079092,-0.067772,-0.135455,-0.147025,-0.122248,-0.171722,0.001650,-0.240998,0.040984
2020-03-11,-0.048748,-0.055960,-0.034730,-0.045302,-0.047070,-0.039814,-0.032942,-0.066829,-0.003560,-0.038420,-0.029959
2020-03-12,-0.095677,-0.122368,-0.098755,-0.094838,-0.082430,-0.095280,-0.114340,-0.149609,-0.039888,-0.071808,-0.019702
2020-03-16,-0.109424,-0.184521,-0.128647,-0.147390,-0.149649,-0.153973,-0.095225,-0.158245,-0.011446,-0.112260,-0.028892
2020-03-18,-0.050633,-0.066507,-0.024480,-0.042096,-0.105269,-0.054140,-0.100245,-0.157444,-0.019922,-0.134006,-0.072296
2020-03-20,-0.043094,-0.033901,-0.063486,-0.037559,-0.021102,-0.072170,-0.049085,0.043261,0.014996,-0.052336,-0.030230
2020-04-01,-0.045005,-0.077883,-0.052617,-0.035508,-0.062979,-0.068771,-0.011588,0.012038,0.009456,0.087951,-0.032317
2020-04-21,-0.030363,-0.061104,-0.030910,-0.041358,-0.029004,-0.038222,-0.005342,-0.016428,-0.006825,-0.244036,-0.053534
2020-06-11,-0.057649,-0.060907,-0.048010,-0.053698,-0.083443,-0.100376,-0.088253,-0.084414,-0.007214,-0.076204,0.018539
2020-09-03,-0.034414,-0.092775,-0.080061,-0.061947,-0.003148,-0.006966,-0.002041,-0.003444,-0.008104,-0.008103,0.000402
2020-10-28,-0.034179,-0.057458,-0.046312,-0.049566,-0.028088,-0.015933,-0.038086,-0.045060,-0.016143,-0.050485,-0.007618
2022-04-29,-0.036956,-0.062431,-0.036605,-0.041812,-0.032268,-0.030698,-0.022362,-0.028016,-0.000113,0.016265,0.051684
2022-05-05,-0.035543,-0.073276,-0.055716,-0.043555,-0.025020,-0.027965,-0.015158,-0.000527,-0.003811,0.006900,0.043731
2022-05-09,-0.032017,-0.092369,-0.033189,-0.036946,-0.015034,-0.028838,-0.078853,-0.058059,-0.014479,-0.057389,-0.126445
2022-05-18,-0.040312,-0.068163,-0.056419,-0.045530,-0.017106,-0.030842,-0.015851,-0.002050,0.000531,-0.025194,0.007707
2022-06-13,-0.037968,-0.078178,-0.038285,-0.042413,-0.029778,-0.034670,-0.045889,-0.035530,-0.026412,0.002131,-0.027232
2022-06-16,-0.033096,-0.056030,-0.039651,-0.026970,-0.017156,-0.006240,-0.036885,-0.046579,0.011243,0.010969,0.005930
2022-08-26,-0.033849,-0.092280,-0.037699,-0.038587,-0.032729,-0.031588,-0.012312,0.002558,-0.012153,0.016610,-0.008427
2022-09-13,-0.043483,-0.094726,-0.058680,-0.054979,-0.034749,-0.036008,-0.023358,-0.014823,-0.013011,-0.008830,0.004243
2025-04-03,-0.049281,-0.078065,-0.092456,-0.023630,-0.069685,-0.110633,-0.052583,-0.040567,-0.006038,-0.064176,0.020469
2025-04-04,-0.058543,-0.073576,-0.072887,-0.035566,-0.074838,-0.076034,-0.071956,-0.080837,-0.023392,-0.065013,-0.072740
2025-04-10,-0.043819,-0.059127,-0.042394,-0.023406,-0.030853,-0.034993,-0.055482,-0.064329,0.024424,-0.032834,-0.067872

In [ ]:
# On affiche le nombre de jours de crash, la plus petite / grande date, top 5 rendements les plus faibles

print(len(crash_days))
print(crash_days.index.min().date())
print(crash_days.index.max().date())
crash_days["S&P 500"].nsmallest(5)

46
2010-02-04
2025-04-10

Date
2020-03-16   -0.109424
2020-03-12   -0.095677
2020-03-09   -0.078094
2011-08-08   -0.065123
2025-04-04   -0.058543
Name: S&P 500, dtype: float64

In [31]:
crash_days

Ticker,S&P 500,Nvidia,Apple,Microsoft,JPMorgan,Bank of America,Exxon Mobil,Shell,Gold,Oil,Gas
Date,,,,,,,,,,,
2010-02-04,-0.030866,-0.058057,-0.036039,-0.027594,-0.048151,-0.050225,-0.028228,-0.040719,-0.039834,-0.049921,-0.000554
2010-05-06,-0.033213,-0.020690,-0.038048,-0.029146,-0.042693,-0.071306,-0.034457,-0.034561,0.029542,-0.033652,-0.015535
2010-05-20,-0.037760,-0.023511,-0.042603,-0.040014,-0.039360,-0.061925,-0.033947,-0.017351,-0.006774,-0.025105,-0.012506
2010-06-04,-0.035137,-0.047245,-0.027212,-0.039836,-0.037851,-0.029095,-0.032976,-0.042175,0.010427,-0.044026,0.022814
2010-06-29,-0.030875,-0.055855,-0.045211,-0.041135,-0.038402,-0.043963,-0.020181,-0.031593,0.001487,-0.027710,-0.035828
2011-08-04,-0.046841,-0.095206,-0.038719,-0.036404,-0.049624,-0.074424,-0.049923,-0.070524,-0.005264,-0.052813,-0.036430
2011-08-08,-0.065123,-0.078764,-0.054628,-0.046729,-0.094149,-0.203182,-0.061882,-0.068168,0.033199,-0.051477,-0.001522
2011-08-10,-0.044178,-0.045630,-0.027593,-0.053948,-0.055769,-0.109210,-0.044120,-0.040356,0.035407,0.040070,0.002253
2011-08-18,-0.043118,-0.067916,-0.037825,-0.022970,-0.037736,-0.060322,-0.043420,-0.036077,0.018920,-0.032640,-0.010425
2011-09-22,-0.032325,-0.066344,-0.025040,-0.035783,-0.035267,-0.050157,-0.037932,-0.023753,-0.026154,-0.044128,-0.006702
2011-11-09,-0.036910,-0.050398,-0.026955,-0.035346,-0.070817,-0.056661,-0.029715,-0.049910,-0.008413,-0.023391,-0.024833
2015-08-21,-0.030103,-0.031137,-0.061163,-0.056723,-0.035487,-0.037081,-0.032721,-0.032294,0.006248,-0.024882,-0.028675
2015-08-24,-0.042107,-0.035398,-0.024962,-0.032273,-0.052673,-0.050310,-0.047276,-0.051678,-0.005399,-0.060933,-0.009716
2016-06-24,-0.035909,-0.056919,-0.028096,-0.040069,-0.069477,-0.074074,-0.026253,-0.064347,0.049038,-0.049106,-0.013343
2018-02-05,-0.041822,-0.084875,-0.024985,-0.041186,-0.047952,-0.052895,-0.056903,-0.041010,0.002532,-0.013998,-0.034786
2018-02-08,-0.037509,-0.049301,-0.027517,-0.051334,-0.044210,-0.048320,-0.011308,-0.022116,0.001523,-0.010685,-0.001850
2018-10-10,-0.031664,-0.074753,-0.046326,-0.054338,-0.026633,-0.024683,-0.023003,-0.020202,0.002487,-0.022471,0.005511
2018-10-24,-0.030299,-0.097937,-0.034302,-0.053469,-0.018623,-0.030718,-0.027806,-0.027888,0.002320,-0.003532,-0.014321
2018-12-04,-0.032402,-0.076041,-0.043989,-0.031849,-0.044637,-0.054310,-0.022039,-0.018597,0.006099,0.006322,0.027195
2019-08-05,-0.030073,-0.064520,-0.052348,-0.034258,-0.029753,-0.044248,-0.020488,-0.022941,0.013982,-0.033608,-0.024045
2020-02-24,-0.033165,-0.070697,-0.047500,-0.043116,-0.026876,-0.047439,-0.046846,-0.038438,0.008985,-0.037607,-0.040945
2020-02-25,-0.030302,-0.041093,-0.033872,-0.016502,-0.044643,-0.050412,-0.038325,-0.029188,-0.017874,-0.023979,0.010947
2020-02-27,-0.044912,-0.055666,-0.065368,-0.070459,-0.041614,-0.048971,-0.060177,-0.039563,0.000195,-0.023395,-0.037891
2020-03-05,-0.033242,-0.039436,-0.032437,-0.025095,-0.049061,-0.050691,-0.044067,-0.034658,0.021601,-0.022296,-0.030104
2020-03-09,-0.078094,-0.077432,-0.079092,-0.067772,-0.135455,-0.147025,-0.122248,-0.171722,0.001650,-0.240998,0.040984
2020-03-11,-0.048748,-0.055960,-0.034730,-0.045302,-0.047070,-0.039814,-0.032942,-0.066829,-0.003560,-0.038420,-0.029959
2020-03-12,-0.095677,-0.122368,-0.098755,-0.094838,-0.082430,-0.095280,-0.114340,-0.149609,-0.039888,-0.071808,-0.019702
2020-03-16,-0.109424,-0.184521,-0.128647,-0.147390,-0.149649,-0.153973,-0.095225,-0.158245,-0.011446,-0.112260,-0.028892
2020-03-18,-0.050633,-0.066507,-0.024480,-0.042096,-0.105269,-0.054140,-0.100245,-0.157444,-0.019922,-0.134006,-0.072296
2020-03-20,-0.043094,-0.033901,-0.063486,-0.037559,-0.021102,-0.072170,-0.049085,0.043261,0.014996,-0.052336,-0.030230
2020-04-01,-0.045005,-0.077883,-0.052617,-0.035508,-0.062979,-0.068771,-0.011588,0.012038,0.009456,0.087951,-0.032317
2020-04-21,-0.030363,-0.061104,-0.030910,-0.041358,-0.029004,-0.038222,-0.005342,-0.016428,-0.006825,-0.244036,-0.053534
2020-06-11,-0.057649,-0.060907,-0.048010,-0.053698,-0.083443,-0.100376,-0.088253,-0.084414,-0.007214,-0.076204,0.018539
2020-09-03,-0.034414,-0.092775,-0.080061,-0.061947,-0.003148,-0.006966,-0.002041,-0.003444,-0.008104,-0.008103,0.000402
2020-10-28,-0.034179,-0.057458,-0.046312,-0.049566,-0.028088,-0.015933,-0.038086,-0.045060,-0.016143,-0.050485,-0.007618
2022-04-29,-0.036956,-0.062431,-0.036605,-0.041812,-0.032268,-0.030698,-0.022362,-0.028016,-0.000113,0.016265,0.051684
2022-05-05,-0.035543,-0.073276,-0.055716,-0.043555,-0.025020,-0.027965,-0.015158,-0.000527,-0.003811,0.006900,0.043731
2022-05-09,-0.032017,-0.092369,-0.033189,-0.036946,-0.015034,-0.028838,-0.078853,-0.058059,-0.014479,-0.057389,-0.126445
2022-05-18,-0.040312,-0.068163,-0.056419,-0.045530,-0.017106,-0.030842,-0.015851,-0.002050,0.000531,-0.025194,0.007707
2022-06-13,-0.037968,-0.078178,-0.038285,-0.042413,-0.029778,-0.034670,-0.045889,-0.035530,-0.026412,0.002131,-0.027232
2022-06-16,-0.033096,-0.056030,-0.039651,-0.026970,-0.017156,-0.006240,-0.036885,-0.046579,0.011243,0.010969,0.005930
2022-08-26,-0.033849,-0.092280,-0.037699,-0.038587,-0.032729,-0.031588,-0.012312,0.002558,-0.012153,0.016610,-0.008427
2022-09-13,-0.043483,-0.094726,-0.058680,-0.054979,-0.034749,-0.036008,-0.023358,-0.014823,-0.013011,-0.008830,0.004243
2025-04-03,-0.049281,-0.078065,-0.092456,-0.023630,-0.069685,-0.110633,-0.052583,-0.040567,-0.006038,-0.064176,0.020469
2025-04-04,-0.058543,-0.073576,-0.072887,-0.035566,-0.074838,-0.076034,-0.071956,-0.080837,-0.023392,-0.065013,-0.072740
2025-04-10,-0.043819,-0.059127,-0.042394,-0.023406,-0.030853,-0.034993,-0.055482,-0.064329,0.024424,-0.032834,-0.067872