In [1]:
import numpy as np
import yfinance as yf
import pandas as pd

In [2]:
tickers = [
    "SPY",   # S&P 500 ETF
    "AAPL",  # Apple
    "NVDA",  # Nvidia
    "MSFT",  # Microsoft
    "JPM",   # JPMorgan Chase
    "BAC",   # Bank of America
    "SHEL",  # Shell
    "XOM",   # Exxon Mobil
    "GLD",   # SPDR Gold Shares
    "BZ=F",  # Brent crude oil futures
    "NG=F"   # Natural gas (Henry Hub) futures
]

START_DATE = "2010-01-01"
END_DATE = "2026-09-14"

In [3]:
data = yf.download(
    tickers,
    start=START_DATE,
    end=END_DATE,
    interval="1d",
    auto_adjust=True,
    progress=False
)

In [4]:
data

Price            Close                                                 \
Ticker            AAPL        BAC        BZ=F         GLD         JPM
Date
2010-01-04    6.400959  11.977124   80.120003  109.800003   28.152390
2010-01-05    6.412026  12.366439   80.589996  109.699997   28.697681
2010-01-06    6.310035  12.511476   81.889999  111.510002   28.855375
2010-01-07    6.298370  12.923689   81.510002  110.820000   29.426962
2010-01-08    6.340243  12.809187   81.370003  111.370003   29.354694
...                ...        ...         ...         ...         ...
2026-09-04  319.970001  62.680000   96.279999  406.769989  358.640015
2026-09-08  316.220001  62.389999   97.919998  399.720001  353.510010
2026-09-09  315.339996  62.669998  101.209999  403.350006  354.709991
2026-09-10  326.570007  62.560001  107.629997  396.359985  353.559998
2026-09-11  332.269989  62.689999  104.610001  398.769989  356.230011

Price                                                             ...  \
Ticker            MSFT   NG=F        NVDA       SHEL         SPY  ...
Date                                                              ...
2010-01-04   22.984234  5.884    0.422817  26.799500   84.578484  ...
2010-01-05   22.991669  5.637    0.428991  26.829580   84.802368  ...
2010-01-06   22.850563  6.009    0.431736  26.610369   84.862076  ...
2010-01-07   22.612923  5.806    0.423275  26.481426   85.220299  ...
2010-01-08   22.768877  5.749    0.424189  26.442736   85.503899  ...
...                ...    ...         ...        ...         ...  ...
2026-09-04  499.700012  2.975  230.102524  92.949997  770.190002  ...
2026-09-08  493.950012  2.916  225.477692  95.320000  765.960022  ...
2026-09-09  491.649994  2.822  223.419998  95.599998  762.400024  ...
2026-09-10  492.440002  2.834  218.360001  95.959999  757.830017  ...
2026-09-11  495.630005  2.831  218.289993  96.769997  764.289978  ...

Price            Volume                                               \
Ticker              BAC     BZ=F         GLD         JPM        MSFT
Date
2010-01-04  180845200.0     97.0  16224100.0  35460500.0  38409100.0
2010-01-05  209521300.0     97.0  14213100.0  41208300.0  49749600.0
2010-01-06  205257900.0      7.0  24981900.0  27729000.0  58182400.0
2010-01-07  320868400.0      7.0  13609800.0  44864700.0  50559700.0
2010-01-08  220104700.0      7.0  15894600.0  33110100.0  51197400.0
...                 ...      ...         ...         ...         ...
2026-09-04   26587200.0  35106.0   9813200.0   4873500.0  18101800.0
2026-09-08   28338000.0  71135.0   8992200.0   5631400.0  18882300.0
2026-09-09   36015200.0  51567.0   8188400.0   6318200.0  12889600.0
2026-09-10   29359100.0  72538.0  10202900.0   4184200.0  16038800.0
2026-09-11   28873700.0  72538.0  10943000.0   5354600.0  14510500.0

Price
Ticker          NG=F         NVDA       SHEL          SPY         XOM
Date
2010-01-04   78858.0  800204000.0  1643003.0  118944600.0  27809100.0
2010-01-05   99492.0  728648000.0  1718458.0  111579900.0  30174700.0
2010-01-06  140611.0  649168000.0  3040554.0  116074400.0  35044700.0
2010-01-07  135113.0  547792000.0  1033089.0  131091100.0  27192100.0
2010-01-08  101153.0  478168000.0  1438017.0  126402800.0  24891800.0
...              ...          ...        ...          ...         ...
2026-09-04  150051.0  135352400.0  6849003.0   34054200.0  16206400.0
2026-09-08  248447.0  122965600.0  7425065.0   44746100.0  12607700.0
2026-09-09  178990.0   82955500.0  8384823.0   32812400.0  13124000.0
2026-09-10  174179.0  105768000.0  6483274.0   42740400.0  16615300.0
2026-09-11  174179.0   88804100.0  4906624.0   45477300.0  11362400.0

[4201 rows x 55 columns]

In [5]:
data = data["Close"].sort_index()

In [6]:
data.tail()

Ticker,AAPL,BAC,BZ=F,GLD,JPM,MSFT,NG=F,NVDA,SHEL,SPY,XOM
Date,,,,,,,,,,,
2026-09-04,319.970001,62.680000,96.279999,406.769989,358.640015,499.700012,2.975,230.102524,92.949997,770.190002,159.470001
2026-09-08,316.220001,62.389999,97.919998,399.720001,353.510010,493.950012,2.916,225.477692,95.320000,765.960022,160.660004
2026-09-09,315.339996,62.669998,101.209999,403.350006,354.709991,491.649994,2.822,223.419998,95.599998,762.400024,164.229996
2026-09-10,326.570007,62.560001,107.629997,396.359985,353.559998,492.440002,2.834,218.360001,95.959999,757.830017,165.229996
2026-09-11,332.269989,62.689999,104.610001,398.769989,356.230011,495.630005,2.831,218.289993,96.769997,764.289978,165.990005

In [7]:
data

Ticker,AAPL,BAC,BZ=F,GLD,JPM,MSFT,NG=F,NVDA,SHEL,SPY,XOM
Date,,,,,,,,,,,
2010-01-04,6.400959,11.977124,80.120003,109.800003,28.152390,22.984234,5.884,0.422817,26.799500,84.578484,37.136810
2010-01-05,6.412026,12.366439,80.589996,109.699997,28.697681,22.991669,5.637,0.428991,26.829580,84.802368,37.281811
2010-01-06,6.310035,12.511476,81.889999,111.510002,28.855375,22.850563,6.009,0.431736,26.610369,84.862076,37.604038
2010-01-07,6.298370,12.923689,81.510002,110.820000,29.426962,22.612923,5.806,0.423275,26.481426,85.220299,37.485893
2010-01-08,6.340243,12.809187,81.370003,111.370003,29.354694,22.768877,5.749,0.424189,26.442736,85.503899,37.335526
...,...,...,...,...,...,...,...,...,...,...,...
2026-09-04,319.970001,62.680000,96.279999,406.769989,358.640015,499.700012,2.975,230.102524,92.949997,770.190002,159.470001
2026-09-08,316.220001,62.389999,97.919998,399.720001,353.510010,493.950012,2.916,225.477692,95.320000,765.960022,160.660004
2026-09-09,315.339996,62.669998,101.209999,403.350006,354.709991,491.649994,2.822,223.419998,95.599998,762.400024,164.229996
2026-09-10,326.570007,62.560001,107.629997,396.359985,353.559998,492.440002,2.834,218.360001,95.959999,757.830017,165.229996
2026-09-11,332.269989,62.689999,104.610001,398.769989,356.230011,495.630005,2.831,218.289993,96.769997,764.289978,165.990005

In [8]:
# date orrdre croissant
data.tail(10)

Ticker,AAPL,BAC,BZ=F,GLD,JPM,MSFT,NG=F,NVDA,SHEL,SPY,XOM
Date,,,,,,,,,,,
2026-08-28,319.700012,62.003654,89.309998,408.890015,357.619995,513.530029,2.888,217.306839,90.910004,769.349976,156.710007
2026-08-31,316.850006,61.625580,90.489998,408.420013,356.019989,507.290009,2.935,220.533234,91.449997,767.049988,160.949997
2026-09-01,325.130005,61.675331,94.650002,396.750000,354.950012,501.019989,2.904,217.196976,93.510002,761.780029,164.550003
2026-09-02,324.959991,62.282230,95.629997,402.779999,356.220001,496.820007,2.956,224.159180,92.800003,765.159973,164.149994
2026-09-03,328.209991,62.719997,95.519997,410.220001,362.059998,510.119995,2.913,228.194656,92.330002,773.169983,162.210007
2026-09-04,319.970001,62.680000,96.279999,406.769989,358.640015,499.700012,2.975,230.102524,92.949997,770.190002,159.470001
2026-09-08,316.220001,62.389999,97.919998,399.720001,353.510010,493.950012,2.916,225.477692,95.320000,765.960022,160.660004
2026-09-09,315.339996,62.669998,101.209999,403.350006,354.709991,491.649994,2.822,223.419998,95.599998,762.400024,164.229996
2026-09-10,326.570007,62.560001,107.629997,396.359985,353.559998,492.440002,2.834,218.360001,95.959999,757.830017,165.229996
2026-09-11,332.269989,62.689999,104.610001,398.769989,356.230011,495.630005,2.831,218.289993,96.769997,764.289978,165.990005

In [12]:
data.rename(columns={
    
    "SPY": "S&P 500",
    "AAPL": "Apple",
    "NVDA": "Nvidia",
    "MSFT": "Microsoft",
    "JPM": "JPMorgan",
    "BAC": "Bank of America",
    "SHEL": "Shell",
    "XOM": "Exxon Mobil",
    "GLD": "Gold",
    "BZ=F": "Oil",
    "NG=F": "Gas"
    
},inplace = True)

In [13]:
data.head(10)

Ticker,Apple,Bank of America,Oil,Gold,JPMorgan,Microsoft,Gas,Nvidia,Shell,S&P 500,Exxon Mobil
Date,,,,,,,,,,,
2010-01-04,6.400959,11.977124,80.120003,109.800003,28.152390,22.984234,5.884,0.422817,26.799500,84.578484,37.136810
2010-01-05,6.412026,12.366439,80.589996,109.699997,28.697681,22.991669,5.637,0.428991,26.829580,84.802368,37.281811
2010-01-06,6.310035,12.511476,81.889999,111.510002,28.855375,22.850563,6.009,0.431736,26.610369,84.862076,37.604038
2010-01-07,6.298370,12.923689,81.510002,110.820000,29.426962,22.612923,5.806,0.423275,26.481426,85.220299,37.485893
2010-01-08,6.340243,12.809187,81.370003,111.370003,29.354694,22.768877,5.749,0.424189,26.442736,85.503899,37.335526
2010-01-11,6.284314,12.923689,80.970001,112.849998,29.256134,22.479250,5.454,0.418244,26.855375,85.623291,37.754433
2010-01-12,6.212829,12.488573,79.300003,110.489998,28.572857,22.330729,5.591,0.404066,26.249331,84.824791,37.566452
2010-01-13,6.300462,12.687049,78.309998,111.540001,29.072184,22.538664,5.733,0.409554,26.266516,85.541229,37.416080
2010-01-14,6.263976,12.839724,77.820000,112.029999,29.361256,22.991669,5.588,0.403151,26.202042,85.772552,37.421448
2010-01-15,6.159291,12.412237,77.110001,110.860001,28.697681,22.917400,5.691,0.391260,26.008619,84.809853,37.115322

In [ ]:
# savoir le nombre de NaN
data.isna().sum()

Ticker
Apple               3
Bank of America     3
Oil                34
Gold                3
JPMorgan            3
Microsoft           3
Gas                 2
Nvidia              3
Shell               3
S&P 500             3
Exxon Mobil         3
dtype: int64

In [18]:
data.dropna(inplace=True)
data.isna().sum()

Ticker
Apple              0
Bank of America    0
Oil                0
Gold               0
JPMorgan           0
Microsoft          0
Gas                0
Nvidia             0
Shell              0
S&P 500            0
Exxon Mobil        0
dtype: int64

In [19]:
data

Ticker,Apple,Bank of America,Oil,Gold,JPMorgan,Microsoft,Gas,Nvidia,Shell,S&P 500,Exxon Mobil
Date,,,,,,,,,,,
2010-01-04,6.400959,11.977124,80.120003,109.800003,28.152390,22.984234,5.884,0.422817,26.799500,84.578484,37.136810
2010-01-05,6.412026,12.366439,80.589996,109.699997,28.697681,22.991669,5.637,0.428991,26.829580,84.802368,37.281811
2010-01-06,6.310035,12.511476,81.889999,111.510002,28.855375,22.850563,6.009,0.431736,26.610369,84.862076,37.604038
2010-01-07,6.298370,12.923689,81.510002,110.820000,29.426962,22.612923,5.806,0.423275,26.481426,85.220299,37.485893
2010-01-08,6.340243,12.809187,81.370003,111.370003,29.354694,22.768877,5.749,0.424189,26.442736,85.503899,37.335526
...,...,...,...,...,...,...,...,...,...,...,...
2026-09-04,319.970001,62.680000,96.279999,406.769989,358.640015,499.700012,2.975,230.102524,92.949997,770.190002,159.470001
2026-09-08,316.220001,62.389999,97.919998,399.720001,353.510010,493.950012,2.916,225.477692,95.320000,765.960022,160.660004
2026-09-09,315.339996,62.669998,101.209999,403.350006,354.709991,491.649994,2.822,223.419998,95.599998,762.400024,164.229996
2026-09-10,326.570007,62.560001,107.629997,396.359985,353.559998,492.440002,2.834,218.360001,95.959999,757.830017,165.229996
2026-09-11,332.269989,62.689999,104.610001,398.769989,356.230011,495.630005,2.831,218.289993,96.769997,764.289978,165.990005

In [20]:
data.columns

Index(['Apple', 'Bank of America', 'Oil', 'Gold', 'JPMorgan', 'Microsoft',
       'Gas', 'Nvidia', 'Shell', 'S&P 500', 'Exxon Mobil'],
      dtype='object', name='Ticker')

In [21]:
column = ["S&P 500", "Nvidia", "Apple", "Microsoft", "JPMorgan", "Bank of America", "Exxon Mobil", "Shell", "Gold", "Oil", "Gas" ]
data = data[column]

In [22]:
data

Ticker,S&P 500,Nvidia,Apple,Microsoft,JPMorgan,Bank of America,Exxon Mobil,Shell,Gold,Oil,Gas
Date,,,,,,,,,,,
2010-01-04,84.578484,0.422817,6.400959,22.984234,28.152390,11.977124,37.136810,26.799500,109.800003,80.120003,5.884
2010-01-05,84.802368,0.428991,6.412026,22.991669,28.697681,12.366439,37.281811,26.829580,109.699997,80.589996,5.637
2010-01-06,84.862076,0.431736,6.310035,22.850563,28.855375,12.511476,37.604038,26.610369,111.510002,81.889999,6.009
2010-01-07,85.220299,0.423275,6.298370,22.612923,29.426962,12.923689,37.485893,26.481426,110.820000,81.510002,5.806
2010-01-08,85.503899,0.424189,6.340243,22.768877,29.354694,12.809187,37.335526,26.442736,111.370003,81.370003,5.749
...,...,...,...,...,...,...,...,...,...,...,...
2026-09-04,770.190002,230.102524,319.970001,499.700012,358.640015,62.680000,159.470001,92.949997,406.769989,96.279999,2.975
2026-09-08,765.960022,225.477692,316.220001,493.950012,353.510010,62.389999,160.660004,95.320000,399.720001,97.919998,2.916
2026-09-09,762.400024,223.419998,315.339996,491.649994,354.709991,62.669998,164.229996,95.599998,403.350006,101.209999,2.822
2026-09-10,757.830017,218.360001,326.570007,492.440002,353.559998,62.560001,165.229996,95.959999,396.359985,107.629997,2.834
2026-09-11,764.289978,218.289993,332.269989,495.630005,356.230011,62.689999,165.990005,96.769997,398.769989,104.610001,2.831